version: 2
jobs:
  build:
    working_directory: ~/ridesharing_app
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          PGHOST: localhost
          PGUSER: bett
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: bett
          POSTGRES_DB: rideshare_test
          POSTGRES_PASSWORD: ""
      - image: circleci/node:10.8.0-browsers
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: ridesharing_app-{{ checksum "Gemfile.lock" }}

      - run: sudo apt-get install nodejs

      # Bundle install dependencies
      - run: gem install bundler
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: ridesharing_app-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bin/rails db:migrate

      # Run the tests
      - run: bin/rails test